### ISSUE TITLE
Invalid channel error after transaction signing in v0.3.3 update

### ISSUE THREAD

**Issue by ixje** [LedgerHQ/app-neo3#27]
Ledger released version `v0.3.3` of the NEO app which breaks all wallets using a nano-s. The nano-s plus and Nano X do not seem to be affected. It was tested with these firmware versions
```
Nano X v2.2.3
Nano S v2.1.0
Nano S Plus v1.1.1
```

The error happens after transaction signing
![image](https://github.com/LedgerHQ/app-neo3/assets/6625537/40e5a96f-47a1-4fcd-a0ff-a8802a96d8fe)

The above is a screenshot of the [neon-wallet](https://neon.coz.io/) app, but other wallets like `O3` and `NeoLine` have the same problem.

**Comment by ixje** [comment]
Here's is a Python script to reproduce the error: [gist](https://gist.github.com/ixje/0d2f44427fc3e8122dbfea676efcb4db)

This is the same as the [cli.py](https://github.com/LedgerHQ/app-neo3/blob/develop/cli.py) in this repo, but updated to work with the Python SDK (and stripped slightly for brevity).

Steps to reproduce
- install Python 3.11 or 3.12
- `pip install neo-mamba==2.6.0 ledgerblue`
- open the neo3 app, go to settings and change contract data to allowed (press both buttons at same time)
- run `python cli.py`, review the transaction and choose accept. It will now throw the error
![Screenshot from 2024-05-23 09-39-42](https://github.com/LedgerHQ/app-neo3/assets/6625537/be14f320-cb56-44f9-87c0-a5b0582df6eb)

**Comment by yogh333** [comment]
@ixje Hi, the issue has been fixed in the last `0.4.0` release (head of `develop` branch)
